### ISSUE TITLE
AST2VEC

### ISSUE THREAD

**Issue by RoyLQ** [RoyLQ/Advanced_AutoCodeCompletion#9]
Given an AST for JS code, the expected output should be a numerical vector that is acceptable by any NN.

**Comment by RoyLQ** [comment]
pls comment ur potential solutions here

**Comment by BraidenKirkland** [comment]
This paper used the same JavaScript data set that we have access to. They mention traversing the ASTs. I have not read too much into this particular paper yet. I will have a closer look at it later.

[automatic_code_completion_Stanford.pdf](https://github.com/RoyLQ/Advanced_AutoCodeCompletion/files/7487782/automatic_code_completion_Stanford.pdf)

**Comment by SNett00** [comment]
I am going to read through that document. It actually seems like exactly what we need to do. I took it upon myself to also send those authors an email explaining what we are doing and if they could possibly lend a hand.

**Comment by RoyLQ** [comment]
Done by approaching the skipgarm.
